#!/bin/sh

# Xcode Cloud post-clone step.
#
# This project's `Its404Yo.xcodeproj` is generated by XcodeGen from `project.yml` and is NOT
# committed (see .gitignore / CLAUDE.md). Xcode Cloud clones the repo without it, so we install
# XcodeGen and regenerate the project before Xcode Cloud resolves the scheme and builds.

set -e

brew install xcodegen

cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

# Xcode Cloud runs with automatic package resolution disabled and requires a committed
# Package.resolved. Ours lives inside the generated (uncommitted) .xcodeproj, so we keep a tracked
# baseline (ci_scripts/Package.resolved.baseline) and drop it into place after generating the
# project. Xcode Cloud's resolve step then uses the pinned versions instead of re-resolving.
# Maintenance: when a dependency changes, re-resolve locally and refresh the baseline:
#   xcodebuild -resolvePackageDependencies -project Its404Yo.xcodeproj -scheme Its404Yo
#   cp Its404Yo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved ci_scripts/Package.resolved.baseline
SWIFTPM_DIR="Its404Yo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
mkdir -p "$SWIFTPM_DIR"
cp ci_scripts/Package.resolved.baseline "$SWIFTPM_DIR/Package.resolved"
