#!/bin/sh

# Xcode Cloud post-clone step.
#
# This project's `Its404Yo.xcodeproj` is generated by XcodeGen from `project.yml` and is NOT
# committed (see .gitignore / CLAUDE.md). Xcode Cloud clones the repo without it, so we install
# XcodeGen and regenerate the project before Xcode Cloud resolves the scheme and builds.

set -e

brew install xcodegen

cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

# The generated .xcodeproj (and its Package.resolved) is not committed, and Xcode Cloud runs
# with automatic package resolution disabled. Resolve here so Package.resolved exists before
# Xcode Cloud's own dependency-resolution step.
xcodebuild -resolvePackageDependencies -project Its404Yo.xcodeproj -scheme Its404Yo
