"""Write site/sitemap.xml with lastmod dates that are true.

Run:  make sitemap      (the Pages deploy runs this too, so the served sitemap is always current)

lastmod is the date of the last commit that touched each page's HTML. Google only uses lastmod
from sites whose dates it can trust; a hand-written date that never moves (or a build date stamped
on every page) gets the field ignored, and changed pages wait for Google's own recrawl.

Every page in site/ is listed unless it carries a noindex robots meta, so a new page cannot be
forgotten. changefreq and priority are omitted: Google ignores both.

Needs full git history. In a shallow clone every page would get the same, wrong date, so the
script refuses to run there rather than publish one.
"""
import subprocess, sys
from pathlib import Path

BASE = "https://its404yo.iamjarl.com/"
ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"

def git(*args):
    return subprocess.run(["git", "-C", str(ROOT), *args], capture_output=True, text=True, check=True).stdout.strip()

def main():
    if git("rev-parse", "--is-shallow-repository") == "true":
        sys.exit("shallow clone: lastmod would be wrong for every page. Fetch full history (fetch-depth: 0).")
    pages = sorted(SITE.glob("*.html"), key=lambda p: (p.name != "index.html", p.name))
    rows = []
    for page in pages:
        html = page.read_text(encoding="utf-8").lower()
        if 'name="robots"' in html and "noindex" in html.split('name="robots"', 1)[1][:80]:
            continue
        date = git("log", "-1", "--format=%cs", "--", str(page.relative_to(ROOT)))
        if not date:
            sys.exit(f"{page.name} has no commit yet; commit it before generating the sitemap")
        loc = BASE if page.name == "index.html" else BASE + page.name
        rows.append(f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{date}</lastmod>\n  </url>")
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!-- Generated by scripts/sitemap.py from git history. Do not edit by hand. -->\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
           + "\n".join(rows) + "\n</urlset>\n")
    (SITE / "sitemap.xml").write_text(xml, encoding="utf-8")
    for r in rows:
        print(r.split("<loc>")[1].split("</loc>")[0].replace(BASE, "/"), r.split("<lastmod>")[1][:10])

if __name__ == "__main__":
    main()
